[workspace]
name = "common_ros2_interfaces"
channels = ["robostack-humble", "conda-forge"]
preview = ["pixi-build"]
platforms = ["linux-64"]

[dependencies]
perceive_semantix_interfaces = { path = "perceive_semantix_interfaces/"}